Views_Helpers/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get 'products' => 'users#lala'

  match 'holamundo', to: 'users#holamundo', via: [:get]

end

Views_Helpers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Views_Helpers/app/controllers/users_controller.rb
class UsersController < ApplicationController

  #Permite que pueda utilizar render js
  # ActionController::RequestForgeryProtection - Ruby on Rails API
  protect_from_forgery except: :index

  def index
    @array_nombres = ["Diana Ortiz", "Jesus Huerta", "Laura Zavala", "Roberto Perez"]

    #render solo texto
    #render plain: "OK"

    #render de html
    #render html: "<strong>Not Found</strong>".html_safe

    #render inline: "xml.p {'Horrid coding practice!'}", type: :builder

    #render xml: @array_nombres

    #render body: "raw"

    #render inline: "<% @array_nombres.each do |p| %><p><%= p %></p><% end %>"

    #Esto no funciona, investigarlo
    #render js: "alert('Hello Rails');"

    #render status: 500
    #render status: :forbidden

  end

  def holamundo
    p "hola"
    p params
    render :_profile
  end


end

Views_Helpers/app/helpers/application_helper.rb
module ApplicationHelper
end

Views_Helpers/app/helpers/users_helper.rb
module UsersHelper
end

Views_Helpers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ViewsHelpers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Views_Helpers/app/views/users/_profile.html.erb
<h1>Users#_profile</h1>
<p>Find me in app/views/users/_profile.html.erb</p>

Views_Helpers/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @array_nombres.each do |p| %>

  <div><%= p %></div>

<% end %>

<!-- Render de un partial sin la _ inicial y su nombre en comillas-->
<%= render 'profile' %>

<!-- En este link mando parametros se obtienen en el controlador con params -->
<%= link_to "Nuevo link", holamundo_path(@array_nombres) %>


<!-- En este link con una ruta simple -->
<%= link_to "Nuevo link", holamundo_path %>

<br><br>  

<%= button_to "Nuevo Boton", action: "holamundo" %>
<!-- 
#  "<form method="post" action="/controller/new" class="button_to">
#      <input value="New" type="submit" />
#    </form>"
-->
<br><br>

<%= image_tag("http://icon-icons.com/icons2/625/PNG/512/big-smile-smiley_icon-icons.com_57417.png", size: "150x150") %>

<!-- image_tag("icon")
# => <img alt="Icon" src="/assets/icon" />
image_tag("icon.png")
# => <img alt="Icon" src="/assets/icon.png" />
image_tag("icon.png", size: "16x10", alt: "Edit Entry")
# => <img src="/assets/icon.png" width="16" height="10" alt="Edit Entry" />
image_tag("/icons/icon.gif", size: "16")
# => <img src="/icons/icon.gif" width="16" height="16" alt="Icon" />
image_tag("/icons/icon.gif", height: '32', width: '32')
# => <img alt="Icon" height="32" src="/icons/icon.gif" width="32" />
image_tag("/icons/icon.gif", class: "menu_icon")
# => <img alt="Icon" class="menu_icon" src="/icons/icon.gif" /> -->

<br><br>


<%= form_for :person do |f| %>
  First name: <%= f.text_field :first_name %><br />
  Last name : <%= f.text_field :last_name %><br />
  Biography : <%= f.text_area :biography %><br />
  Admin?    : <%= f.check_box :admin %><br />
  <%= f.submit %>
<% end %>

<!--
<#%= #form_for @post, as: :post, url: post_path(@post), method: :patch, html: { class: "edit_post", id: "edit_post_45" } do |f| %>

<#% #end %>-->

Views_Helpers/app/views/users/lala.html.erb
<h1>Hola</h1>